Fix & speedup of database build process | Update docker containers
open-discourse/open-discourse pull request #146
Opened 2024-07-11 15:17 UTC by insalt-glitch

The following changes are made to the build process of the database (in python):
1. The [fuzzywuzzy](https://pypi.org/project/fuzzywuzzy/)-package is replaced with the much faster [levenshtein](https://pypi.org/project/Levenshtein/)-package (Speedup ~1.5 hour).
2. The minimum python version is bumped to 3.8 (due to the [levenshtein](https://pypi.org/project/Levenshtein/)-package).
3. The build-in [os-module](https://docs.python.org/3/library/os.html) is replaced with the modern built-in [pathlib-module](https://docs.python.org/3/library/pathlib.html). This cleans up the handling of file paths in the all scripts.
4. Major speed improvements were gained by getting rid of most `pandas.concat`- and `pandas.append`-calls. This also removes/future-proofs against the deprecation warning of [pandas.append](https://pandas.pydata.org/pandas-docs/version/1.3/reference/api/pandas.DataFrame.append.html). The speed-up at least ~2 hours.
5. The [suggested workaround](https://github.com/open-discourse/open-discourse/issues/138) is added to fix the fatal error. Closes #138 .
6. The script which is responsible for parsing Wikipedia for the members of the government is fixed.
7. A minimalistic progress-bar was added to view the progress of the build as suggested [here](https://github.com/open-discourse/open-discourse/issues/54). A more refined version could be added.

2024-07-11 20:47 UTC, insalt-glitch commented
There are still some bugs in the build, and I'll also fix #141 and #142, but it would still be nice if someone could explain to me why the database cannot be properly initialized with the yarn command anymore.

2024-07-11 21:21 UTC, JabobKrauskopf commented
Thank you for the PR, it is very much appreciated! :)

I have reserved my working day on monday to work on Open Discourse. I'll try to get the database scripts working again, take a look at your PR and will also do a small refactoring of the setup (Makefile, pyproject.toml, linting, formatting, etc.). That should be a small step in the right direction to improve this (currently) terrible code base :D

2024-07-15 14:03 UTC, JabobKrauskopf commented on python/src/od_lib/01_preprocessing/03_split_xml.py
> +    if not folder_path.is_dir():
could you add a bit more spacing between these code blocks? :)

2024-07-15 14:04 UTC, JabobKrauskopf commented on python/src/od_lib/01_preprocessing/04_split_xml_electoral_term_1_and_2.py
> +    if not folder_path.is_dir():
could you also add a bit more spacing here?

2024-07-15 14:05 UTC, JabobKrauskopf commented on python/src/od_lib/01_preprocessing/05_split_xml_electoral_term_19_20.py
> +    if not folder_path.is_dir():
could you also add a bit more spacing here?

2024-07-15 18:12 UTC, insalt-glitch commented
I'll continue working here on Friday or next week. Sorry, no time before...

2024-07-15 18:29 UTC, JabobKrauskopf commented
@insalt-glitch No worries, take your time :)
Thank you so much for your work

2024-07-18 07:32 UTC, insalt-glitch commented
Okay, the branch is up-to-date with main now. All the things you commented on in review should be fixed. In my opinion, it would be nice to have a linter like [pylint](https://pypi.org/project/pylint/) with a settings file in the CI such that everyone is on the same page about the code style in this library.

Furthermore, I have noticed that the access of pandas-DataFrame columns is inconsistent in this project. You can find both `df_name.col_name` and `df_name["col_name"]`. In my opinion, the second option is to be preferred at all times since the dot-notation may collide with methods on the DataFrame itself, e.g. there could be a column named `mean` but there is a method is with the same name.

2024-07-18 08:21 UTC, JabobKrauskopf commented
@insalt-glitch Great, thanks! :)

> In my opinion, it would be nice to have a linter like [pylint](https://pypi.org/project/pylint/) with a settings file in the CI such that everyone is on the same page about the code style in this library.

I agree that we definetly need a linter. I have already setup a linter and formatter (ruff) in the refactoring branch which I will update and merge after this PR is completed.

> You can find both df_name.col_name and df_name["col_name"]. In my opinion, the second option is to be preferred at all times since the dot-notation may collide with methods on the DataFrame itself

Completely agree.

2024-07-18 08:54 UTC, JabobKrauskopf commented
@insalt-glitch I will do a final review of the PR now. I'll get back to you with that.

Is the PR ready to be merged if there are no change requests?

Also: After the refactoring we'll release open-discourse version 2.0.0 and a new open discourse newsletter. Would you consent to us publishing your name or username, whichever you prefer?

2024-07-18 11:52 UTC, JabobKrauskopf requested changes
Only some minor changes now.

I've recreated the database from scratch and must say that the speedup is amazing and the feedback via the progress bar and the console output in general is great and really helpful!

Thank you! :)

2024-07-18 11:52 UTC, JabobKrauskopf commented on python/src/od_lib/07_database/02_upload_data_to_database.py
The factions dataframe creation also needs to be updated because of the new factions.

This is the updated dataframe
```python
factions = pd.DataFrame.from_records(
    [
        {
            "id": -1,
            "abbreviation": "not found",
            "full_name": "not found",
        },
        {
            "id": 0,
            "abbreviation": "AfD",
            "full_name": "Alternative für Deutschland",
        },
        {
            "id": 1,
            "abbreviation": "BHE",
            "full_name": "Block der Heimatvertriebenen und Entrechteten",
        },
        {
            "id": 2,
            "abbreviation": "BP",
            "full_name": "Bayernpartei",
        },
        {
            "id": 3,
            "abbreviation": "BSW",
            "full_name": "Bündnis Sahra Wagenknecht",
        },
        {
            "id": 4,
            "abbreviation": "Grüne",
            "full_name": "Bündnis 90/Die Grünen",
        },
        {
            "id": 5,
            "abbreviation": "CDU/CSU",
            "full_name": "Christlich Demokratische Union Deutschlands/Christlich-Soziale Union in Bayern",
        },
        {
            "id": 6,
            "abbreviation": "DA",
            "full_name": "Demokratische Arbeitsgemeinschaft",
        },
        {
            "id": 7,
            "abbreviation": "DIE LINKE.",
            "full_name": "DIE LINKE.",
        },
        {
            "id": 8,
            "abbreviation": "DP",
            "full_name": "Deutsche Partei",
        },
        {
            "id": 9,
            "abbreviation": "DP/DPB",
            "full_name": "Deutsche Partei/Deutsche Partei Bayern",
        },
        {
            "id": 10,
            "abbreviation": "DP/FVP",
            "full_name": "Deutsche Partei/Freie Volkspartei",
        },
        {
            "id": 11,
            "abbreviation": "DPB",
            "full_name": "Deutsche Partei Bayern",
        },
        {
            "id": 12,
            "abbreviation": "DRP",
            "full_name": "Deutsche Reformpartei",
        },
        {
            "id": 13,
            "abbreviation": "DRP/NR",
            "full_name": "Deutsche Reichspartei/Nationale Rechte",
        },
        {
            "id": 14,
            "abbreviation": "DSU",
            "full_name": "Deutsche Soziale Union",
        },
        {
            "id": 15,
            "abbreviation": "FDP",
            "full_name": "Freie Demokratische Partei",
        },
        {
            "id": 16,
            "abbreviation": "FU",
            "full_name": "Föderalistische Union",
        },
        {
            "id": 17,
            "abbreviation": "FVP",
            "full_name": "Freie Volkspartei",
        },
        {
            "id": 18,
            "abbreviation": "Fraktionslos",
            "full_name": "Fraktionslos",
        },
        {
            "id": 19,
            "abbreviation": "GB/BHE",
            "full_name": "Gesamtdeutscher Block/Bund der Heimatvertriebenen und Entrechteten",
        },
        {
            "id": 20,
            "abbreviation": "Gast",
            "full_name": "Gast",
        },
        {
            "id": 21,
            "abbreviation": "KO",
            "full_name": "Kraft/Oberländer-Gruppe",
        },
        {
            "id": 22,
            "abbreviation": "KPD",
            "full_name": "Kommunistische Partei Deutschlands",
        },
        {
            "id": 23,
            "abbreviation": "NR",
            "full_name": "Nationale Rechte",
        },
        {
            "id": 24,
            "abbreviation": "PDS",
            "full_name": "Partei des Demokratischen Sozialismus",
        },
        {
            "id": 25,
            "abbreviation": "SPD",
            "full_name": "Sozialdemokratische Partei Deutschlands",
        },
        {
            "id": 26,
            "abbreviation": "SSW",
            "full_name": "Südschleswigscher Wählerverband",
        },
        {
            "id": 27,
            "abbreviation": "WAV",
            "full_name": "Wirtschaftliche Aufbau-Vereinigung",
        },
        {
            "id": 28,
            "abbreviation": "Z",
            "full_name": "Deutsche Zentrumspartei",
        },
    ],
)
```

It's not great that this has to be done manually but I'd rather not change it for now :/

2024-07-18 11:52 UTC, JabobKrauskopf commented on python/src/od_lib/06_contributions/01_extract_contributions.py
> +simplified_list = [contributions_simplified]
```suggestion
simplified_list = []
```

this should no longer be needed, no?

2024-07-18 18:01 UTC, insalt-glitch commented on python/src/od_lib/03_politicians/03_merge_politicians.py
> +    "DSU": r"^DSU   ",
They were not! Good catch, thank you!

2024-07-18 18:19 UTC, insalt-glitch commented
> the refactoring we'll release open-discourse version 2.0.0

Sounds good, I prefer my name.

2024-07-18 18:49 UTC, insalt-glitch commented on python/src/od_lib/07_database/02_upload_data_to_database.py
I added this in a slightly different format. Is that fine?

2024-07-18 18:55 UTC, insalt-glitch commented
Everything should be good now, I think.

I had to fix some things in `06_contributions/02_clean_contributions_extended.py` as the indexing was wrong. Not sure how/if it worked before at all. According to pandas documentation, it was assigning to copied values.

I slightly changed `01_preprocessing/07_create_electoral_terms.py` which I think improves readability. However, data format that is stored there still seems completely wild (SQL and pandas both have a type for dates).

2024-07-22 19:40 UTC, JabobKrauskopf commented on python/src/od_lib/07_database/02_upload_data_to_database.py
I think I prefer the above representation because it is more explicit but lets leave it for now. I might change it later on

2024-07-22 19:42 UTC, JabobKrauskopf approved these changes
Thank you so much for your contribution!

2024-07-22 19:44 UTC, merged